// Copyright 2024 Stefan Höck

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void print_code(const char *name, int val) {
  printf("\npublic export %%inline\n");
  printf("%s : Errno\n", name);
  printf("%s = %d\n", name, val);
}

void print_errorcodes() {
  print_code("EPERM", EPERM);
  print_code("ENOENT", ENOENT);
  print_code("ESRCH", ESRCH);
  print_code("EINTR", EINTR);
  print_code("EIO", EIO);
  print_code("ENXIO", ENXIO);
  print_code("E2BIG", E2BIG);
  print_code("ENOEXEC", ENOEXEC);
  print_code("EBADF", EBADF);
  print_code("ECHILD", ECHILD);
  print_code("EAGAIN", EAGAIN);
  print_code("EWOULDBLOCK", EWOULDBLOCK);
  print_code("ENOMEM", ENOMEM);
  print_code("EACCES", EACCES);
  print_code("EFAULT", EFAULT);
  print_code("ENOTBLK", ENOTBLK);
  print_code("EBUSY", EBUSY);
  print_code("EEXIST", EEXIST);
  print_code("EXDEV", EXDEV);
  print_code("ENODEV", ENODEV);
  print_code("ENOTDIR", ENOTDIR);
  print_code("EISDIR", EISDIR);
  print_code("EINVAL", EINVAL);
  print_code("ENFILE", ENFILE);
  print_code("EMFILE", EMFILE);
  print_code("ENOTTY", ENOTTY);
  print_code("ETXTBSY", ETXTBSY);
  print_code("EFBIG", EFBIG);
  print_code("ENOSPC", ENOSPC);
  print_code("ESPIPE", ESPIPE);
  print_code("EROFS", EROFS);
  print_code("EMLINK", EMLINK);
  print_code("EPIPE", EPIPE);
  print_code("EDOM", EDOM);
  print_code("ERANGE", ERANGE);
  print_code("EDEADLK", EDEADLK);
  print_code("ENAMETOOLONG", ENAMETOOLONG);
  print_code("ENOLCK", ENOLCK);
  print_code("ENOSYS", ENOSYS);
  print_code("ENOTEMPTY", ENOTEMPTY);
  print_code("ELOOP", ELOOP);
  print_code("ENOMSG", ENOMSG);
  print_code("EIDRM", EIDRM);
  print_code("ENOSTR", ENOSTR);
  print_code("ENODATA", ENODATA);
  print_code("ETIME", ETIME);
  print_code("ENOSR", ENOSR);
  print_code("EREMOTE", EREMOTE);
  print_code("ENOLINK", ENOLINK);
  print_code("EPROTO", EPROTO);
  print_code("EMULTIHOP", EMULTIHOP);
  print_code("EBADMSG", EBADMSG);
  print_code("EOVERFLOW", EOVERFLOW);
  print_code("EILSEQ", EILSEQ);
  print_code("EUSERS", EUSERS);
  print_code("ENOTSOCK", ENOTSOCK);
  print_code("EDESTADDRREQ", EDESTADDRREQ);
  print_code("EMSGSIZE", EMSGSIZE);
  print_code("EPROTOTYPE", EPROTOTYPE);
  print_code("ENOPROTOOPT", ENOPROTOOPT);
  print_code("EPROTONOSUPPORT", EPROTONOSUPPORT);
  print_code("ESOCKTNOSUPPORT", ESOCKTNOSUPPORT);
  print_code("EOPNOTSUPP", EOPNOTSUPP);
  print_code("EPFNOSUPPORT", EPFNOSUPPORT);
  print_code("EAFNOSUPPORT", EAFNOSUPPORT);
  print_code("EADDRINUSE", EADDRINUSE);
  print_code("EADDRNOTAVAIL", EADDRNOTAVAIL);
  print_code("ENETDOWN", ENETDOWN);
  print_code("ENETUNREACH", ENETUNREACH);
  print_code("ENETRESET", ENETRESET);
  print_code("ECONNABORTED", ECONNABORTED);
  print_code("ECONNRESET", ECONNRESET);
  print_code("ENOBUFS", ENOBUFS);
  print_code("EISCONN", EISCONN);
  print_code("ENOTCONN", ENOTCONN);
  print_code("ESHUTDOWN", ESHUTDOWN);
  print_code("ETOOMANYREFS", ETOOMANYREFS);
  print_code("ETIMEDOUT", ETIMEDOUT);
  print_code("ECONNREFUSED", ECONNREFUSED);
  print_code("EHOSTDOWN", EHOSTDOWN);
  print_code("EHOSTUNREACH", EHOSTUNREACH);
  print_code("EALREADY", EALREADY);
  print_code("EINPROGRESS", EINPROGRESS);
  print_code("ESTALE", ESTALE);
  print_code("EDQUOT", EDQUOT);
  print_code("ECANCELED", ECANCELED);
  print_code("EOWNERDEAD", EOWNERDEAD);
  print_code("ENOTRECOVERABLE", ENOTRECOVERABLE);

#ifdef __GLIBC__
  print_code("ECHRNG", ECHRNG);
  print_code("EL2NSYNC", EL2NSYNC);
  print_code("EL3HLT", EL3HLT);
  print_code("EL3RST", EL3RST);
  print_code("ELNRNG", ELNRNG);
  print_code("EUNATCH", EUNATCH);
  print_code("ENOCSI", ENOCSI);
  print_code("EL2HLT", EL2HLT);
  print_code("EBADE", EBADE);
  print_code("EBADR", EBADR);
  print_code("EXFULL", EXFULL);
  print_code("ENOANO", ENOANO);
  print_code("EBADRQC", EBADRQC);
  print_code("EBADSLT", EBADSLT);
  print_code("EBFONT", EBFONT);
  print_code("ENONET", ENONET);
  print_code("ENOPKG", ENOPKG);
  print_code("EADV", EADV);
  print_code("ESRMNT", ESRMNT);
  print_code("ECOMM", ECOMM);
  print_code("EDOTDOT", EDOTDOT);
  print_code("ENOTUNIQ", ENOTUNIQ);
  print_code("EBADFD", EBADFD);
  print_code("EREMCHG", EREMCHG);
  print_code("ELIBACC", ELIBACC);
  print_code("ELIBBAD", ELIBBAD);
  print_code("ELIBSCN", ELIBSCN);
  print_code("ELIBMAX", ELIBMAX);
  print_code("ELIBEXEC", ELIBEXEC);
  print_code("ERESTART", ERESTART);
  print_code("ESTRPIPE", ESTRPIPE);
  print_code("EUCLEAN", EUCLEAN);
  print_code("ENOTNAM", ENOTNAM);
  print_code("ENAVAIL", ENAVAIL);
  print_code("EISNAM", EISNAM);
  print_code("EREMOTEIO", EREMOTEIO);
  print_code("ENOMEDIUM", ENOMEDIUM);
  print_code("EMEDIUMTYPE", EMEDIUMTYPE);
  print_code("ENOKEY", ENOKEY);
  print_code("EKEYEXPIRED", EKEYEXPIRED);
  print_code("EKEYREVOKED", EKEYREVOKED);
  print_code("EKEYREJECTED", EKEYREJECTED);
  print_code("ERFKILL", ERFKILL);
  print_code("EHWPOISON", EHWPOISON);
#endif
}

void print_errtxt(int val) {
  printf("errorText %d = \"%s\"\n", val, strerror(val));
}

void print_errname(int val, const char *name) {
  printf("errorName %d = \"%s\"\n", val, name);
}

void print_errortexts() {
  printf("\nexport\nerrorText : Errno -> String\n");
  print_errtxt(EPERM);
  print_errtxt(ENOENT);
  print_errtxt(ESRCH);
  print_errtxt(EINTR);
  print_errtxt(EIO);
  print_errtxt(ENXIO);
  print_errtxt(E2BIG);
  print_errtxt(ENOEXEC);
  print_errtxt(EBADF);
  print_errtxt(ECHILD);
  print_errtxt(EAGAIN);
  print_errtxt(ENOMEM);
  print_errtxt(EACCES);
  print_errtxt(EFAULT);
  print_errtxt(ENOTBLK);
  print_errtxt(EBUSY);
  print_errtxt(EEXIST);
  print_errtxt(EXDEV);
  print_errtxt(ENODEV);
  print_errtxt(ENOTDIR);
  print_errtxt(EISDIR);
  print_errtxt(EINVAL);
  print_errtxt(ENFILE);
  print_errtxt(EMFILE);
  print_errtxt(ENOTTY);
  print_errtxt(ETXTBSY);
  print_errtxt(EFBIG);
  print_errtxt(ENOSPC);
  print_errtxt(ESPIPE);
  print_errtxt(EROFS);
  print_errtxt(EMLINK);
  print_errtxt(EPIPE);
  print_errtxt(EDOM);
  print_errtxt(ERANGE);
  print_errtxt(EDEADLK);
  print_errtxt(ENAMETOOLONG);
  print_errtxt(ENOLCK);
  print_errtxt(ENOSYS);
  print_errtxt(ENOTEMPTY);
  print_errtxt(ELOOP);
  print_errtxt(ENOMSG);
  print_errtxt(EIDRM);
  print_errtxt(ENOSTR);
  print_errtxt(ENODATA);
  print_errtxt(ETIME);
  print_errtxt(ENOSR);
  print_errtxt(EREMOTE);
  print_errtxt(ENOLINK);
  print_errtxt(EPROTO);
  print_errtxt(EMULTIHOP);
  print_errtxt(EBADMSG);
  print_errtxt(EOVERFLOW);
  print_errtxt(EILSEQ);
  print_errtxt(EUSERS);
  print_errtxt(ENOTSOCK);
  print_errtxt(EDESTADDRREQ);
  print_errtxt(EMSGSIZE);
  print_errtxt(EPROTOTYPE);
  print_errtxt(ENOPROTOOPT);
  print_errtxt(EPROTONOSUPPORT);
  print_errtxt(ESOCKTNOSUPPORT);
  print_errtxt(EOPNOTSUPP);
  print_errtxt(EPFNOSUPPORT);
  print_errtxt(EAFNOSUPPORT);
  print_errtxt(EADDRINUSE);
  print_errtxt(EADDRNOTAVAIL);
  print_errtxt(ENETDOWN);
  print_errtxt(ENETUNREACH);
  print_errtxt(ENETRESET);
  print_errtxt(ECONNABORTED);
  print_errtxt(ECONNRESET);
  print_errtxt(ENOBUFS);
  print_errtxt(EISCONN);
  print_errtxt(ENOTCONN);
  print_errtxt(ESHUTDOWN);
  print_errtxt(ETOOMANYREFS);
  print_errtxt(ETIMEDOUT);
  print_errtxt(ECONNREFUSED);
  print_errtxt(EHOSTDOWN);
  print_errtxt(EHOSTUNREACH);
  print_errtxt(EALREADY);
  print_errtxt(EINPROGRESS);
  print_errtxt(ESTALE);
  print_errtxt(EDQUOT);
  print_errtxt(ECANCELED);
  print_errtxt(EOWNERDEAD);
  print_errtxt(ENOTRECOVERABLE);
#ifdef __GLIBC__
  print_errtxt(ECHRNG);
  print_errtxt(EL2NSYNC);
  print_errtxt(EL3HLT);
  print_errtxt(EL3RST);
  print_errtxt(ELNRNG);
  print_errtxt(EUNATCH);
  print_errtxt(ENOCSI);
  print_errtxt(EL2HLT);
  print_errtxt(EBADE);
  print_errtxt(EBADR);
  print_errtxt(EXFULL);
  print_errtxt(ENOANO);
  print_errtxt(EBADRQC);
  print_errtxt(EBADSLT);
  print_errtxt(EBFONT);
  print_errtxt(ENONET);
  print_errtxt(ENOPKG);
  print_errtxt(EADV);
  print_errtxt(ESRMNT);
  print_errtxt(ECOMM);
  print_errtxt(EDOTDOT);
  print_errtxt(ENOTUNIQ);
  print_errtxt(EBADFD);
  print_errtxt(EREMCHG);
  print_errtxt(ELIBACC);
  print_errtxt(ELIBBAD);
  print_errtxt(ELIBSCN);
  print_errtxt(ELIBMAX);
  print_errtxt(ELIBEXEC);
  print_errtxt(ERESTART);
  print_errtxt(ESTRPIPE);
  print_errtxt(EUCLEAN);
  print_errtxt(ENOTNAM);
  print_errtxt(ENAVAIL);
  print_errtxt(EISNAM);
  print_errtxt(EREMOTEIO);
  print_errtxt(ENOMEDIUM);
  print_errtxt(EMEDIUMTYPE);
  print_errtxt(ENOKEY);
  print_errtxt(EKEYEXPIRED);
  print_errtxt(EKEYREVOKED);
  print_errtxt(EKEYREJECTED);
  print_errtxt(ERFKILL);
  print_errtxt(EHWPOISON);
#endif
  printf("errorText (EN x) = \"Unknown error: \\{show x}\"\n");
}

void print_errornames() {
  printf("\nexport\nerrorName : Errno -> String\n");
  print_errname(EPERM, "EPERM");
  print_errname(ENOENT, "ENOENT");
  print_errname(ESRCH, "ESRCH");
  print_errname(EINTR, "EINTR");
  print_errname(EIO, "EIO");
  print_errname(ENXIO, "ENXIO");
  print_errname(E2BIG, "E2BIG");
  print_errname(ENOEXEC, "ENOEXEC");
  print_errname(EBADF, "EBADF");
  print_errname(ECHILD, "ECHILD");
  print_errname(EAGAIN, "EAGAIN");
  print_errname(ENOMEM, "ENOMEM");
  print_errname(EACCES, "EACCES");
  print_errname(EFAULT, "EFAULT");
  print_errname(ENOTBLK, "ENOTBLK");
  print_errname(EBUSY, "EBUSY");
  print_errname(EEXIST, "EEXIST");
  print_errname(EXDEV, "EXDEV");
  print_errname(ENODEV, "ENODEV");
  print_errname(ENOTDIR, "ENOTDIR");
  print_errname(EISDIR, "EISDIR");
  print_errname(EINVAL, "EINVAL");
  print_errname(ENFILE, "ENFILE");
  print_errname(EMFILE, "EMFILE");
  print_errname(ENOTTY, "ENOTTY");
  print_errname(ETXTBSY, "ETXTBSY");
  print_errname(EFBIG, "EFBIG");
  print_errname(ENOSPC, "ENOSPC");
  print_errname(ESPIPE, "ESPIPE");
  print_errname(EROFS, "EROFS");
  print_errname(EMLINK, "EMLINK");
  print_errname(EPIPE, "EPIPE");
  print_errname(EDOM, "EDOM");
  print_errname(ERANGE, "ERANGE");
  print_errname(EDEADLK, "EDEADLK");
  print_errname(ENAMETOOLONG, "ENAMETOOLONG");
  print_errname(ENOLCK, "ENOLCK");
  print_errname(ENOSYS, "ENOSYS");
  print_errname(ENOTEMPTY, "ENOTEMPTY");
  print_errname(ELOOP, "ELOOP");
  print_errname(ENOMSG, "ENOMSG");
  print_errname(EIDRM, "EIDRM");
  print_errname(ENOSTR, "ENOSTR");
  print_errname(ENODATA, "ENODATA");
  print_errname(ETIME, "ETIME");
  print_errname(ENOSR, "ENOSR");
  print_errname(EREMOTE, "EREMOTE");
  print_errname(ENOLINK, "ENOLINK");
  print_errname(EPROTO, "EPROTO");
  print_errname(EMULTIHOP, "EMULTIHOP");
  print_errname(EBADMSG, "EBADMSG");
  print_errname(EOVERFLOW, "EOVERFLOW");
  print_errname(EILSEQ, "EILSEQ");
  print_errname(EUSERS, "EUSERS");
  print_errname(ENOTSOCK, "ENOTSOCK");
  print_errname(EDESTADDRREQ, "EDESTADDRREQ");
  print_errname(EMSGSIZE, "EMSGSIZE");
  print_errname(EPROTOTYPE, "EPROTOTYPE");
  print_errname(ENOPROTOOPT, "ENOPROTOOPT");
  print_errname(EPROTONOSUPPORT, "EPROTONOSUPPORT");
  print_errname(ESOCKTNOSUPPORT, "ESOCKTNOSUPPORT");
  print_errname(EOPNOTSUPP, "EOPNOTSUPP");
  print_errname(EPFNOSUPPORT, "EPFNOSUPPORT");
  print_errname(EAFNOSUPPORT, "EAFNOSUPPORT");
  print_errname(EADDRINUSE, "EADDRINUSE");
  print_errname(EADDRNOTAVAIL, "EADDRNOTAVAIL");
  print_errname(ENETDOWN, "ENETDOWN");
  print_errname(ENETUNREACH, "ENETUNREACH");
  print_errname(ENETRESET, "ENETRESET");
  print_errname(ECONNABORTED, "ECONNABORTED");
  print_errname(ECONNRESET, "ECONNRESET");
  print_errname(ENOBUFS, "ENOBUFS");
  print_errname(EISCONN, "EISCONN");
  print_errname(ENOTCONN, "ENOTCONN");
  print_errname(ESHUTDOWN, "ESHUTDOWN");
  print_errname(ETOOMANYREFS, "ETOOMANYREFS");
  print_errname(ETIMEDOUT, "ETIMEDOUT");
  print_errname(ECONNREFUSED, "ECONNREFUSED");
  print_errname(EHOSTDOWN, "EHOSTDOWN");
  print_errname(EHOSTUNREACH, "EHOSTUNREACH");
  print_errname(EALREADY, "EALREADY");
  print_errname(EINPROGRESS, "EINPROGRESS");
  print_errname(ESTALE, "ESTALE");
  print_errname(EDQUOT, "EDQUOT");
  print_errname(ECANCELED, "ECANCELED");
  print_errname(EOWNERDEAD, "EOWNERDEAD");
  print_errname(ENOTRECOVERABLE, "ENOTRECOVERABLE");
#ifdef __GLIBC__
  print_errname(ECHRNG, "ECHRNG");
  print_errname(EL2NSYNC, "EL2NSYNC");
  print_errname(EL3HLT, "EL3HLT");
  print_errname(EL3RST, "EL3RST");
  print_errname(ELNRNG, "ELNRNG");
  print_errname(EUNATCH, "EUNATCH");
  print_errname(ENOCSI, "ENOCSI");
  print_errname(EL2HLT, "EL2HLT");
  print_errname(EBADE, "EBADE");
  print_errname(EBADR, "EBADR");
  print_errname(EXFULL, "EXFULL");
  print_errname(ENOANO, "ENOANO");
  print_errname(EBADRQC, "EBADRQC");
  print_errname(EBADSLT, "EBADSLT");
  print_errname(EBFONT, "EBFONT");
  print_errname(ENONET, "ENONET");
  print_errname(ENOPKG, "ENOPKG");
  print_errname(EADV, "EADV");
  print_errname(ESRMNT, "ESRMNT");
  print_errname(ECOMM, "ECOMM");
  print_errname(EDOTDOT, "EDOTDOT");
  print_errname(ENOTUNIQ, "ENOTUNIQ");
  print_errname(EBADFD, "EBADFD");
  print_errname(EREMCHG, "EREMCHG");
  print_errname(ELIBACC, "ELIBACC");
  print_errname(ELIBBAD, "ELIBBAD");
  print_errname(ELIBSCN, "ELIBSCN");
  print_errname(ELIBMAX, "ELIBMAX");
  print_errname(ELIBEXEC, "ELIBEXEC");
  print_errname(ERESTART, "ERESTART");
  print_errname(ESTRPIPE, "ESTRPIPE");
  print_errname(EUCLEAN, "EUCLEAN");
  print_errname(ENOTNAM, "ENOTNAM");
  print_errname(ENAVAIL, "ENAVAIL");
  print_errname(EISNAM, "EISNAM");
  print_errname(EREMOTEIO, "EREMOTEIO");
  print_errname(ENOMEDIUM, "ENOMEDIUM");
  print_errname(EMEDIUMTYPE, "EMEDIUMTYPE");
  print_errname(ENOKEY, "ENOKEY");
  print_errname(EKEYEXPIRED, "EKEYEXPIRED");
  print_errname(EKEYREVOKED, "EKEYREVOKED");
  print_errname(EKEYREJECTED, "EKEYREJECTED");
  print_errname(ERFKILL, "ERFKILL");
  print_errname(EHWPOISON, "EHWPOISON");
#endif
  printf("errorName (EN _) = \"EUNKNOWN\"\n");
}

int main() {
  print_errorcodes();
  print_errortexts();
  print_errornames();

  exit(0);
}
