// Copyright 2024 Stefan Höck

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void *print_errortype() {
  printf("public export\ndata Error : Type where\n");
  printf("  EPERM : Error\n");
  printf("  ENOENT : Error\n");
  printf("  ESRCH : Error\n");
  printf("  EINTR : Error\n");
  printf("  EIO : Error\n");
  printf("  ENXIO : Error\n");
  printf("  E2BIG : Error\n");
  printf("  ENOEXEC : Error\n");
  printf("  EBADF : Error\n");
  printf("  ECHILD : Error\n");
  printf("  EAGAIN : Error\n");
  printf("  ENOMEM : Error\n");
  printf("  EACCES : Error\n");
  printf("  EFAULT : Error\n");
  printf("  ENOTBLK : Error\n");
  printf("  EBUSY : Error\n");
  printf("  EEXIST : Error\n");
  printf("  EXDEV : Error\n");
  printf("  ENODEV : Error\n");
  printf("  ENOTDIR : Error\n");
  printf("  EISDIR : Error\n");
  printf("  EINVAL : Error\n");
  printf("  ENFILE : Error\n");
  printf("  EMFILE : Error\n");
  printf("  ENOTTY : Error\n");
  printf("  ETXTBSY : Error\n");
  printf("  EFBIG : Error\n");
  printf("  ENOSPC : Error\n");
  printf("  ESPIPE : Error\n");
  printf("  EROFS : Error\n");
  printf("  EMLINK : Error\n");
  printf("  EPIPE : Error\n");
  printf("  EDOM : Error\n");
  printf("  ERANGE : Error\n");
  printf("  EDEADLK : Error\n");
  printf("  ENAMETOOLONG : Error\n");
  printf("  ENOLCK : Error\n");
  printf("  ENOSYS : Error\n");
  printf("  ENOTEMPTY : Error\n");
  printf("  ELOOP : Error\n");
  printf("  ENOMSG : Error\n");
  printf("  EIDRM : Error\n");
  printf("  ECHRNG : Error\n");
  printf("  EL2NSYNC : Error\n");
  printf("  EL3HLT : Error\n");
  printf("  EL3RST : Error\n");
  printf("  ELNRNG : Error\n");
  printf("  EUNATCH : Error\n");
  printf("  ENOCSI : Error\n");
  printf("  EL2HLT : Error\n");
  printf("  EBADE : Error\n");
  printf("  EBADR : Error\n");
  printf("  EXFULL : Error\n");
  printf("  ENOANO : Error\n");
  printf("  EBADRQC : Error\n");
  printf("  EBADSLT : Error\n");
  printf("  EDEADLOCK : Error\n");
  printf("  EBFONT : Error\n");
  printf("  ENOSTR : Error\n");
  printf("  ENODATA : Error\n");
  printf("  ETIME : Error\n");
  printf("  ENOSR : Error\n");
  printf("  ENONET : Error\n");
  printf("  ENOPKG : Error\n");
  printf("  EREMOTE : Error\n");
  printf("  ENOLINK : Error\n");
  printf("  EADV : Error\n");
  printf("  ESRMNT : Error\n");
  printf("  ECOMM : Error\n");
  printf("  EPROTO : Error\n");
  printf("  EMULTIHOP : Error\n");
  printf("  EDOTDOT : Error\n");
  printf("  EBADMSG : Error\n");
  printf("  EOVERFLOW : Error\n");
  printf("  ENOTUNIQ : Error\n");
  printf("  EBADFD : Error\n");
  printf("  EREMCHG : Error\n");
  printf("  ELIBACC : Error\n");
  printf("  ELIBBAD : Error\n");
  printf("  ELIBSCN : Error\n");
  printf("  ELIBMAX : Error\n");
  printf("  ELIBEXEC : Error\n");
  printf("  EILSEQ : Error\n");
  printf("  ERESTART : Error\n");
  printf("  ESTRPIPE : Error\n");
  printf("  EUSERS : Error\n");
  printf("  ENOTSOCK : Error\n");
  printf("  EDESTADDRREQ : Error\n");
  printf("  EMSGSIZE : Error\n");
  printf("  EPROTOTYPE : Error\n");
  printf("  ENOPROTOOPT : Error\n");
  printf("  EPROTONOSUPPORT : Error\n");
  printf("  ESOCKTNOSUPPORT : Error\n");
  printf("  EOPNOTSUPP : Error\n");
  printf("  EPFNOSUPPORT : Error\n");
  printf("  EAFNOSUPPORT : Error\n");
  printf("  EADDRINUSE : Error\n");
  printf("  EADDRNOTAVAIL : Error\n");
  printf("  ENETDOWN : Error\n");
  printf("  ENETUNREACH : Error\n");
  printf("  ENETRESET : Error\n");
  printf("  ECONNABORTED : Error\n");
  printf("  ECONNRESET : Error\n");
  printf("  ENOBUFS : Error\n");
  printf("  EISCONN : Error\n");
  printf("  ENOTCONN : Error\n");
  printf("  ESHUTDOWN : Error\n");
  printf("  ETOOMANYREFS : Error\n");
  printf("  ETIMEDOUT : Error\n");
  printf("  ECONNREFUSED : Error\n");
  printf("  EHOSTDOWN : Error\n");
  printf("  EHOSTUNREACH : Error\n");
  printf("  EALREADY : Error\n");
  printf("  EINPROGRESS : Error\n");
  printf("  ESTALE : Error\n");
  printf("  EUCLEAN : Error\n");
  printf("  ENOTNAM : Error\n");
  printf("  ENAVAIL : Error\n");
  printf("  EISNAM : Error\n");
  printf("  EREMOTEIO : Error\n");
  printf("  EDQUOT : Error\n");
  printf("  ENOMEDIUM : Error\n");
  printf("  EMEDIUMTYPE : Error\n");
  printf("  ECANCELED : Error\n");
  printf("  ENOKEY : Error\n");
  printf("  EKEYEXPIRED : Error\n");
  printf("  EKEYREVOKED : Error\n");
  printf("  EKEYREJECTED : Error\n");
  printf("  EOWNERDEAD : Error\n");
  printf("  ENOTRECOVERABLE : Error\n");
  printf("  ERFKILL : Error\n");
  printf("  EHWPOISON : Error\n");
  printf("  EOTHER : Error\n");

  printf("\n%runElab derive \"Error\" [Show,Eq,Ord,Finite]\n\n");
}

void *print_errorcodes() {
  printf("public export\nerrorCode : Error -> Bits32\n");
  printf("errorCode EPERM = %d\n", EPERM);
  printf("errorCode ENOENT = %d\n", ENOENT);
  printf("errorCode ESRCH = %d\n", ESRCH);
  printf("errorCode EINTR = %d\n", EINTR);
  printf("errorCode EIO = %d\n", EIO);
  printf("errorCode ENXIO = %d\n", ENXIO);
  printf("errorCode E2BIG = %d\n", E2BIG);
  printf("errorCode ENOEXEC = %d\n", ENOEXEC);
  printf("errorCode EBADF = %d\n", EBADF);
  printf("errorCode ECHILD = %d\n", ECHILD);
  printf("errorCode EAGAIN = %d\n", EAGAIN);
  printf("errorCode ENOMEM = %d\n", ENOMEM);
  printf("errorCode EACCES = %d\n", EACCES);
  printf("errorCode EFAULT = %d\n", EFAULT);
  printf("errorCode ENOTBLK = %d\n", ENOTBLK);
  printf("errorCode EBUSY = %d\n", EBUSY);
  printf("errorCode EEXIST = %d\n", EEXIST);
  printf("errorCode EXDEV = %d\n", EXDEV);
  printf("errorCode ENODEV = %d\n", ENODEV);
  printf("errorCode ENOTDIR = %d\n", ENOTDIR);
  printf("errorCode EISDIR = %d\n", EISDIR);
  printf("errorCode EINVAL = %d\n", EINVAL);
  printf("errorCode ENFILE = %d\n", ENFILE);
  printf("errorCode EMFILE = %d\n", EMFILE);
  printf("errorCode ENOTTY = %d\n", ENOTTY);
  printf("errorCode ETXTBSY = %d\n", ETXTBSY);
  printf("errorCode EFBIG = %d\n", EFBIG);
  printf("errorCode ENOSPC = %d\n", ENOSPC);
  printf("errorCode ESPIPE = %d\n", ESPIPE);
  printf("errorCode EROFS = %d\n", EROFS);
  printf("errorCode EMLINK = %d\n", EMLINK);
  printf("errorCode EPIPE = %d\n", EPIPE);
  printf("errorCode EDOM = %d\n", EDOM);
  printf("errorCode ERANGE = %d\n", ERANGE);
  printf("errorCode EDEADLK = %d\n", EDEADLK);
  printf("errorCode ENAMETOOLONG = %d\n", ENAMETOOLONG);
  printf("errorCode ENOLCK = %d\n", ENOLCK);
  printf("errorCode ENOSYS = %d\n", ENOSYS);
  printf("errorCode ENOTEMPTY = %d\n", ENOTEMPTY);
  printf("errorCode ELOOP = %d\n", ELOOP);
  printf("errorCode ENOMSG = %d\n", ENOMSG);
  printf("errorCode EIDRM = %d\n", EIDRM);
  printf("errorCode ECHRNG = %d\n", ECHRNG);
  printf("errorCode EL2NSYNC = %d\n", EL2NSYNC);
  printf("errorCode EL3HLT = %d\n", EL3HLT);
  printf("errorCode EL3RST = %d\n", EL3RST);
  printf("errorCode ELNRNG = %d\n", ELNRNG);
  printf("errorCode EUNATCH = %d\n", EUNATCH);
  printf("errorCode ENOCSI = %d\n", ENOCSI);
  printf("errorCode EL2HLT = %d\n", EL2HLT);
  printf("errorCode EBADE = %d\n", EBADE);
  printf("errorCode EBADR = %d\n", EBADR);
  printf("errorCode EXFULL = %d\n", EXFULL);
  printf("errorCode ENOANO = %d\n", ENOANO);
  printf("errorCode EBADRQC = %d\n", EBADRQC);
  printf("errorCode EBADSLT = %d\n", EBADSLT);
  printf("errorCode EDEADLOCK = %d\n", EDEADLOCK);
  printf("errorCode EBFONT = %d\n", EBFONT);
  printf("errorCode ENOSTR = %d\n", ENOSTR);
  printf("errorCode ENODATA = %d\n", ENODATA);
  printf("errorCode ETIME = %d\n", ETIME);
  printf("errorCode ENOSR = %d\n", ENOSR);
  printf("errorCode ENONET = %d\n", ENONET);
  printf("errorCode ENOPKG = %d\n", ENOPKG);
  printf("errorCode EREMOTE = %d\n", EREMOTE);
  printf("errorCode ENOLINK = %d\n", ENOLINK);
  printf("errorCode EADV = %d\n", EADV);
  printf("errorCode ESRMNT = %d\n", ESRMNT);
  printf("errorCode ECOMM = %d\n", ECOMM);
  printf("errorCode EPROTO = %d\n", EPROTO);
  printf("errorCode EMULTIHOP = %d\n", EMULTIHOP);
  printf("errorCode EDOTDOT = %d\n", EDOTDOT);
  printf("errorCode EBADMSG = %d\n", EBADMSG);
  printf("errorCode EOVERFLOW = %d\n", EOVERFLOW);
  printf("errorCode ENOTUNIQ = %d\n", ENOTUNIQ);
  printf("errorCode EBADFD = %d\n", EBADFD);
  printf("errorCode EREMCHG = %d\n", EREMCHG);
  printf("errorCode ELIBACC = %d\n", ELIBACC);
  printf("errorCode ELIBBAD = %d\n", ELIBBAD);
  printf("errorCode ELIBSCN = %d\n", ELIBSCN);
  printf("errorCode ELIBMAX = %d\n", ELIBMAX);
  printf("errorCode ELIBEXEC = %d\n", ELIBEXEC);
  printf("errorCode EILSEQ = %d\n", EILSEQ);
  printf("errorCode ERESTART = %d\n", ERESTART);
  printf("errorCode ESTRPIPE = %d\n", ESTRPIPE);
  printf("errorCode EUSERS = %d\n", EUSERS);
  printf("errorCode ENOTSOCK = %d\n", ENOTSOCK);
  printf("errorCode EDESTADDRREQ = %d\n", EDESTADDRREQ);
  printf("errorCode EMSGSIZE = %d\n", EMSGSIZE);
  printf("errorCode EPROTOTYPE = %d\n", EPROTOTYPE);
  printf("errorCode ENOPROTOOPT = %d\n", ENOPROTOOPT);
  printf("errorCode EPROTONOSUPPORT = %d\n", EPROTONOSUPPORT);
  printf("errorCode ESOCKTNOSUPPORT = %d\n", ESOCKTNOSUPPORT);
  printf("errorCode EOPNOTSUPP = %d\n", EOPNOTSUPP);
  printf("errorCode EPFNOSUPPORT = %d\n", EPFNOSUPPORT);
  printf("errorCode EAFNOSUPPORT = %d\n", EAFNOSUPPORT);
  printf("errorCode EADDRINUSE = %d\n", EADDRINUSE);
  printf("errorCode EADDRNOTAVAIL = %d\n", EADDRNOTAVAIL);
  printf("errorCode ENETDOWN = %d\n", ENETDOWN);
  printf("errorCode ENETUNREACH = %d\n", ENETUNREACH);
  printf("errorCode ENETRESET = %d\n", ENETRESET);
  printf("errorCode ECONNABORTED = %d\n", ECONNABORTED);
  printf("errorCode ECONNRESET = %d\n", ECONNRESET);
  printf("errorCode ENOBUFS = %d\n", ENOBUFS);
  printf("errorCode EISCONN = %d\n", EISCONN);
  printf("errorCode ENOTCONN = %d\n", ENOTCONN);
  printf("errorCode ESHUTDOWN = %d\n", ESHUTDOWN);
  printf("errorCode ETOOMANYREFS = %d\n", ETOOMANYREFS);
  printf("errorCode ETIMEDOUT = %d\n", ETIMEDOUT);
  printf("errorCode ECONNREFUSED = %d\n", ECONNREFUSED);
  printf("errorCode EHOSTDOWN = %d\n", EHOSTDOWN);
  printf("errorCode EHOSTUNREACH = %d\n", EHOSTUNREACH);
  printf("errorCode EALREADY = %d\n", EALREADY);
  printf("errorCode EINPROGRESS = %d\n", EINPROGRESS);
  printf("errorCode ESTALE = %d\n", ESTALE);
  printf("errorCode EUCLEAN = %d\n", EUCLEAN);
  printf("errorCode ENOTNAM = %d\n", ENOTNAM);
  printf("errorCode ENAVAIL = %d\n", ENAVAIL);
  printf("errorCode EISNAM = %d\n", EISNAM);
  printf("errorCode EREMOTEIO = %d\n", EREMOTEIO);
  printf("errorCode EDQUOT = %d\n", EDQUOT);
  printf("errorCode ENOMEDIUM = %d\n", ENOMEDIUM);
  printf("errorCode EMEDIUMTYPE = %d\n", EMEDIUMTYPE);
  printf("errorCode ECANCELED = %d\n", ECANCELED);
  printf("errorCode ENOKEY = %d\n", ENOKEY);
  printf("errorCode EKEYEXPIRED = %d\n", EKEYEXPIRED);
  printf("errorCode EKEYREVOKED = %d\n", EKEYREVOKED);
  printf("errorCode EKEYREJECTED = %d\n", EKEYREJECTED);
  printf("errorCode EOWNERDEAD = %d\n", EOWNERDEAD);
  printf("errorCode ENOTRECOVERABLE = %d\n", ENOTRECOVERABLE);
  printf("errorCode ERFKILL = %d\n", ERFKILL);
  printf("errorCode EHWPOISON = %d\n", EHWPOISON);
  printf("errorCode EOTHER = 0\n");
}

void *print_errortext() {
  printf("\nexport\nerrorText : Error -> String\n");
  printf("errorText EPERM = \"%s\"\n", strerror(EPERM));
  printf("errorText ENOENT = \"%s\"\n", strerror(ENOENT));
  printf("errorText ESRCH = \"%s\"\n", strerror(ESRCH));
  printf("errorText EINTR = \"%s\"\n", strerror(EINTR));
  printf("errorText EIO = \"%s\"\n", strerror(EIO));
  printf("errorText ENXIO = \"%s\"\n", strerror(ENXIO));
  printf("errorText E2BIG = \"%s\"\n", strerror(E2BIG));
  printf("errorText ENOEXEC = \"%s\"\n", strerror(ENOEXEC));
  printf("errorText EBADF = \"%s\"\n", strerror(EBADF));
  printf("errorText ECHILD = \"%s\"\n", strerror(ECHILD));
  printf("errorText EAGAIN = \"%s\"\n", strerror(EAGAIN));
  printf("errorText ENOMEM = \"%s\"\n", strerror(ENOMEM));
  printf("errorText EACCES = \"%s\"\n", strerror(EACCES));
  printf("errorText EFAULT = \"%s\"\n", strerror(EFAULT));
  printf("errorText ENOTBLK = \"%s\"\n", strerror(ENOTBLK));
  printf("errorText EBUSY = \"%s\"\n", strerror(EBUSY));
  printf("errorText EEXIST = \"%s\"\n", strerror(EEXIST));
  printf("errorText EXDEV = \"%s\"\n", strerror(EXDEV));
  printf("errorText ENODEV = \"%s\"\n", strerror(ENODEV));
  printf("errorText ENOTDIR = \"%s\"\n", strerror(ENOTDIR));
  printf("errorText EISDIR = \"%s\"\n", strerror(EISDIR));
  printf("errorText EINVAL = \"%s\"\n", strerror(EINVAL));
  printf("errorText ENFILE = \"%s\"\n", strerror(ENFILE));
  printf("errorText EMFILE = \"%s\"\n", strerror(EMFILE));
  printf("errorText ENOTTY = \"%s\"\n", strerror(ENOTTY));
  printf("errorText ETXTBSY = \"%s\"\n", strerror(ETXTBSY));
  printf("errorText EFBIG = \"%s\"\n", strerror(EFBIG));
  printf("errorText ENOSPC = \"%s\"\n", strerror(ENOSPC));
  printf("errorText ESPIPE = \"%s\"\n", strerror(ESPIPE));
  printf("errorText EROFS = \"%s\"\n", strerror(EROFS));
  printf("errorText EMLINK = \"%s\"\n", strerror(EMLINK));
  printf("errorText EPIPE = \"%s\"\n", strerror(EPIPE));
  printf("errorText EDOM = \"%s\"\n", strerror(EDOM));
  printf("errorText ERANGE = \"%s\"\n", strerror(ERANGE));
  printf("errorText EDEADLK = \"%s\"\n", strerror(EDEADLK));
  printf("errorText ENAMETOOLONG = \"%s\"\n", strerror(ENAMETOOLONG));
  printf("errorText ENOLCK = \"%s\"\n", strerror(ENOLCK));
  printf("errorText ENOSYS = \"%s\"\n", strerror(ENOSYS));
  printf("errorText ENOTEMPTY = \"%s\"\n", strerror(ENOTEMPTY));
  printf("errorText ELOOP = \"%s\"\n", strerror(ELOOP));
  printf("errorText ENOMSG = \"%s\"\n", strerror(ENOMSG));
  printf("errorText EIDRM = \"%s\"\n", strerror(EIDRM));
  printf("errorText ECHRNG = \"%s\"\n", strerror(ECHRNG));
  printf("errorText EL2NSYNC = \"%s\"\n", strerror(EL2NSYNC));
  printf("errorText EL3HLT = \"%s\"\n", strerror(EL3HLT));
  printf("errorText EL3RST = \"%s\"\n", strerror(EL3RST));
  printf("errorText ELNRNG = \"%s\"\n", strerror(ELNRNG));
  printf("errorText EUNATCH = \"%s\"\n", strerror(EUNATCH));
  printf("errorText ENOCSI = \"%s\"\n", strerror(ENOCSI));
  printf("errorText EL2HLT = \"%s\"\n", strerror(EL2HLT));
  printf("errorText EBADE = \"%s\"\n", strerror(EBADE));
  printf("errorText EBADR = \"%s\"\n", strerror(EBADR));
  printf("errorText EXFULL = \"%s\"\n", strerror(EXFULL));
  printf("errorText ENOANO = \"%s\"\n", strerror(ENOANO));
  printf("errorText EBADRQC = \"%s\"\n", strerror(EBADRQC));
  printf("errorText EBADSLT = \"%s\"\n", strerror(EBADSLT));
  printf("errorText EDEADLOCK = \"%s\"\n", strerror(EDEADLOCK));
  printf("errorText EBFONT = \"%s\"\n", strerror(EBFONT));
  printf("errorText ENOSTR = \"%s\"\n", strerror(ENOSTR));
  printf("errorText ENODATA = \"%s\"\n", strerror(ENODATA));
  printf("errorText ETIME = \"%s\"\n", strerror(ETIME));
  printf("errorText ENOSR = \"%s\"\n", strerror(ENOSR));
  printf("errorText ENONET = \"%s\"\n", strerror(ENONET));
  printf("errorText ENOPKG = \"%s\"\n", strerror(ENOPKG));
  printf("errorText EREMOTE = \"%s\"\n", strerror(EREMOTE));
  printf("errorText ENOLINK = \"%s\"\n", strerror(ENOLINK));
  printf("errorText EADV = \"%s\"\n", strerror(EADV));
  printf("errorText ESRMNT = \"%s\"\n", strerror(ESRMNT));
  printf("errorText ECOMM = \"%s\"\n", strerror(ECOMM));
  printf("errorText EPROTO = \"%s\"\n", strerror(EPROTO));
  printf("errorText EMULTIHOP = \"%s\"\n", strerror(EMULTIHOP));
  printf("errorText EDOTDOT = \"%s\"\n", strerror(EDOTDOT));
  printf("errorText EBADMSG = \"%s\"\n", strerror(EBADMSG));
  printf("errorText EOVERFLOW = \"%s\"\n", strerror(EOVERFLOW));
  printf("errorText ENOTUNIQ = \"%s\"\n", strerror(ENOTUNIQ));
  printf("errorText EBADFD = \"%s\"\n", strerror(EBADFD));
  printf("errorText EREMCHG = \"%s\"\n", strerror(EREMCHG));
  printf("errorText ELIBACC = \"%s\"\n", strerror(ELIBACC));
  printf("errorText ELIBBAD = \"%s\"\n", strerror(ELIBBAD));
  printf("errorText ELIBSCN = \"%s\"\n", strerror(ELIBSCN));
  printf("errorText ELIBMAX = \"%s\"\n", strerror(ELIBMAX));
  printf("errorText ELIBEXEC = \"%s\"\n", strerror(ELIBEXEC));
  printf("errorText EILSEQ = \"%s\"\n", strerror(EILSEQ));
  printf("errorText ERESTART = \"%s\"\n", strerror(ERESTART));
  printf("errorText ESTRPIPE = \"%s\"\n", strerror(ESTRPIPE));
  printf("errorText EUSERS = \"%s\"\n", strerror(EUSERS));
  printf("errorText ENOTSOCK = \"%s\"\n", strerror(ENOTSOCK));
  printf("errorText EDESTADDRREQ = \"%s\"\n", strerror(EDESTADDRREQ));
  printf("errorText EMSGSIZE = \"%s\"\n", strerror(EMSGSIZE));
  printf("errorText EPROTOTYPE = \"%s\"\n", strerror(EPROTOTYPE));
  printf("errorText ENOPROTOOPT = \"%s\"\n", strerror(ENOPROTOOPT));
  printf("errorText EPROTONOSUPPORT = \"%s\"\n", strerror(EPROTONOSUPPORT));
  printf("errorText ESOCKTNOSUPPORT = \"%s\"\n", strerror(ESOCKTNOSUPPORT));
  printf("errorText EOPNOTSUPP = \"%s\"\n", strerror(EOPNOTSUPP));
  printf("errorText EPFNOSUPPORT = \"%s\"\n", strerror(EPFNOSUPPORT));
  printf("errorText EAFNOSUPPORT = \"%s\"\n", strerror(EAFNOSUPPORT));
  printf("errorText EADDRINUSE = \"%s\"\n", strerror(EADDRINUSE));
  printf("errorText EADDRNOTAVAIL = \"%s\"\n", strerror(EADDRNOTAVAIL));
  printf("errorText ENETDOWN = \"%s\"\n", strerror(ENETDOWN));
  printf("errorText ENETUNREACH = \"%s\"\n", strerror(ENETUNREACH));
  printf("errorText ENETRESET = \"%s\"\n", strerror(ENETRESET));
  printf("errorText ECONNABORTED = \"%s\"\n", strerror(ECONNABORTED));
  printf("errorText ECONNRESET = \"%s\"\n", strerror(ECONNRESET));
  printf("errorText ENOBUFS = \"%s\"\n", strerror(ENOBUFS));
  printf("errorText EISCONN = \"%s\"\n", strerror(EISCONN));
  printf("errorText ENOTCONN = \"%s\"\n", strerror(ENOTCONN));
  printf("errorText ESHUTDOWN = \"%s\"\n", strerror(ESHUTDOWN));
  printf("errorText ETOOMANYREFS = \"%s\"\n", strerror(ETOOMANYREFS));
  printf("errorText ETIMEDOUT = \"%s\"\n", strerror(ETIMEDOUT));
  printf("errorText ECONNREFUSED = \"%s\"\n", strerror(ECONNREFUSED));
  printf("errorText EHOSTDOWN = \"%s\"\n", strerror(EHOSTDOWN));
  printf("errorText EHOSTUNREACH = \"%s\"\n", strerror(EHOSTUNREACH));
  printf("errorText EALREADY = \"%s\"\n", strerror(EALREADY));
  printf("errorText EINPROGRESS = \"%s\"\n", strerror(EINPROGRESS));
  printf("errorText ESTALE = \"%s\"\n", strerror(ESTALE));
  printf("errorText EUCLEAN = \"%s\"\n", strerror(EUCLEAN));
  printf("errorText ENOTNAM = \"%s\"\n", strerror(ENOTNAM));
  printf("errorText ENAVAIL = \"%s\"\n", strerror(ENAVAIL));
  printf("errorText EISNAM = \"%s\"\n", strerror(EISNAM));
  printf("errorText EREMOTEIO = \"%s\"\n", strerror(EREMOTEIO));
  printf("errorText EDQUOT = \"%s\"\n", strerror(EDQUOT));
  printf("errorText ENOMEDIUM = \"%s\"\n", strerror(ENOMEDIUM));
  printf("errorText EMEDIUMTYPE = \"%s\"\n", strerror(EMEDIUMTYPE));
  printf("errorText ECANCELED = \"%s\"\n", strerror(ECANCELED));
  printf("errorText ENOKEY = \"%s\"\n", strerror(ENOKEY));
  printf("errorText EKEYEXPIRED = \"%s\"\n", strerror(EKEYEXPIRED));
  printf("errorText EKEYREVOKED = \"%s\"\n", strerror(EKEYREVOKED));
  printf("errorText EKEYREJECTED = \"%s\"\n", strerror(EKEYREJECTED));
  printf("errorText EOWNERDEAD = \"%s\"\n", strerror(EOWNERDEAD));
  printf("errorText ENOTRECOVERABLE = \"%s\"\n", strerror(ENOTRECOVERABLE));
  printf("errorText ERFKILL = \"%s\"\n", strerror(ERFKILL));
  printf("errorText EHWPOISON = \"%s\"\n", strerror(EHWPOISON));
  printf("errorText EOTHER = \"Other (unknown) error\"\n");
}

void *main() {
  print_errortype();
  print_errorcodes();
  print_errortext();

  exit(0);
}
