---
name: Darwin Posix Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: posix

jobs:
  darwin-build:
    name: Build Posix lib for Darwin
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            extra-trusted-public-keys = gh-nix-idris2-packages.cachix.org-1:iOqSB5DrESFT+3A1iNzErgB68IDG8BrHLbLkhztOXfo=
            extra-substituters = https://gh-nix-idris2-packages.cachix.org
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build lib
        run: |
          nix-build --expr '
            let buildIdris = ((import (builtins.fetchGit { url = "https://github.com/mattpolzin/nix-idris2-packages.git"; ref = "main"; })) {}).buildIdris'\'';
            in buildIdris { src = ./.; ipkgName = "posix"; }
          '
      - name: Inspect build
        run: nix run nixpkgs#tree -- ./result
